# Each route describes how an incoming URL will be processed by Platform.sh
routes:
  "/*":
    type: upstream
    upstream: "ll_project:http"
  "/static":
    type: static
    root: "static"
    expires: 1h


# Each service listed will be deployed in its own container as part of your
# Platform.sh project

db:
  type: postgresql:12
  disk: 1024
